#!/usr/bin/env python3
"""Generate Morandi-style color palette from Noctalia's Material You colors and apply to system."""

import json
import colorsys
import os
import re
import sys
import subprocess
import argparse
from pathlib import Path

NOCTALIA_COLORS = Path.home() / ".config/noctalia/colors.json"
NIRI_COLORS_KDL = Path.home() / ".config/niri/cfg/colors.kdl"
STARSHIP_TOML = Path.home() / ".config/starship.toml"
FCITX5_THEME = Path.home() / ".local/share/fcitx5/themes/morandi/theme.conf"
FASTFETCH_CONFIG = Path.home() / ".config/fastfetch/config.jsonc"
ALACRITTY_TOML = Path.home() / ".config/alacritty/alacritty.toml"
KDE_OUTPUT = Path.home() / ".local/share/color-schemes/Morandi-dark.colors"
VSCODE_SETTINGS = Path.home() / ".config/Code/User/settings.json"

def hex_to_hsl(hex_color):
    r = int(hex_color[1:3], 16) / 255
    g = int(hex_color[3:5], 16) / 255
    b = int(hex_color[5:7], 16) / 255
    h, l, s = colorsys.rgb_to_hls(r, g, b)
    return h * 360, s * 100, l * 100

def hsl_to_hex(h, s, l):
    h = h % 360
    s = max(0, min(100, s)) / 100
    l = max(0, min(100, l)) / 100
    r, g, b = colorsys.hls_to_rgb(h / 360, l, s)
    return f"#{int(r*255):02x}{int(g*255):02x}{int(b*255):02x}"

def morandi(hex_color, sat_reduction=0.3, light_adjust=0, warm_shift=0, sat_cap=45):
    h, s, l = hex_to_hsl(hex_color)
    s = s * (1 - sat_reduction)
    h = (h + warm_shift) % 360
    l = max(0, min(100, l + light_adjust))
    s = min(s, sat_cap)
    return hsl_to_hex(h, s, l)

def blend(c1, c2, ratio=0.5):
    r1, g1, b1 = int(c1[1:3], 16), int(c1[3:5], 16), int(c1[5:7], 16)
    r2, g2, b2 = int(c2[1:3], 16), int(c2[3:5], 16), int(c2[5:7], 16)
    r = int(r1 + (r2 - r1) * ratio)
    g = int(g1 + (g2 - g1) * ratio)
    b = int(b1 + (b2 - b1) * ratio)
    return f"#{r:02x}{g:02x}{b:02x}"

def generate_palette(c):
    p = {}
    primary = c.get("mPrimary", c.get("primary"))
    secondary = c.get("mSecondary", c.get("secondary"))
    tertiary = c.get("mTertiary", c.get("tertiary"))
    error = c.get("mError", c.get("error"))
    surface = c.get("mSurface", c.get("surface"))
    on_surface = c.get("mOnSurface", c.get("on_surface"))
    surface_var = c.get("mSurfaceVariant", c.get("surface_variant"))
    outline = c.get("mOutline", c.get("outline"))

    p["base"] = morandi(surface, 0.5, -2)
    p["mantle"] = morandi(surface, 0.6, -5)
    p["surface0"] = morandi(surface_var, 0.4, 2)
    p["surface1"] = morandi(surface_var, 0.3, 5)
    p["surface2"] = morandi(surface_var, 0.2, 8)
    p["overlay0"] = morandi(outline, 0.3, -2)
    p["overlay1"] = morandi(outline, 0.2, 2)
    p["overlay2"] = morandi(outline, 0.1, 5)
    p["subtext0"] = morandi(on_surface, 0.4, -8)
    p["subtext1"] = morandi(on_surface, 0.3, -4)
    p["text"] = morandi(on_surface, 0.2, 0)
    p["love"] = morandi(error, 0.25, -15)
    p["rose"] = morandi(blend(primary, error, 0.6), 0.3, -15, 5)
    p["gold"] = morandi(blend(primary, "#d4a574", 0.3), 0.35, -10, 15)
    p["peach"] = morandi(blend(error, "#d4a574", 0.4), 0.3, -10, 10)
    p["pine"] = morandi(tertiary, 0.3, -18, -5)
    p["foam"] = morandi(secondary, 0.35, -18, -5)
    p["iris"] = morandi(primary, 0.25, -18)
    p["sky"] = morandi(tertiary, 0.35, -18, -10)

    h, s, l = hex_to_hsl(p["surface1"])
    p["fcitx5_bg"] = hsl_to_hex(h, s * 0.6, min(l, 20))
    p["fcitx5_bg_alt"] = hsl_to_hex(h, s * 0.5, min(l + 3, 22))
    ih, is_, il = hex_to_hsl(p["iris"])
    p["fcitx5_hl_bg"] = hsl_to_hex(ih, is_, min(il, 38))
    p["fcitx5_text"] = p["text"]
    p["fcitx5_hl_text"] = p["base"]
    return p

def write_niri(palette):
    kdl = f"""// Auto-generated by morandi-gen.py — do not edit manually
layout {{
    focus-ring {{
        width 2
        active-gradient from="{palette['iris']}" to="{palette['pine']}" angle=45
        inactive-gradient from="{palette['surface0']}" to="{palette['surface1']}" angle=45
    }}
    border {{
        off
    }}
    shadow {{
        color "{palette['surface0']}70"
    }}
    tab-indicator {{
        active-color "{palette['iris']}"
        inactive-color "{palette['surface1']}"
        urgent-color "{palette['love']}"
    }}
    insert-hint {{
        color "{palette['iris']}80"
    }}
}}
recent-windows {{
    highlight {{
        active-color "{palette['iris']}"
        urgent-color "{palette['love']}"
    }}
}}
"""
    with open(NIRI_COLORS_KDL, "w") as f:
        f.write(kdl)

def write_starship(palette):
    if not STARSHIP_TOML.exists(): return
    with open(STARSHIP_TOML, "r") as f:
        content = f.read()
    keys = ["base", "mantle", "surface0", "surface1", "surface2", "overlay0", "overlay1", "overlay2", "subtext0", "subtext1", "text", "love", "gold", "peach", "rose", "pine", "foam", "iris", "sky"]
    new_palette = "[palettes.custom]\n" + "\n".join(f"{k} = '{palette[k]}'" for k in keys) + "\n"
    content, count = re.subn(r"\[palettes\.custom\][\s\S]*?(?=\n\[|\Z)", new_palette, content)
    if count == 0: content += "\n" + new_palette
    with open(STARSHIP_TOML, "w") as f:
        f.write(content)

def write_fcitx5(palette):
    theme_dir = FCITX5_THEME.parent
    theme_dir.mkdir(parents=True, exist_ok=True)
    tray_outline, tray_text = palette["surface0"], palette["text"]
    bg, hl = palette['fcitx5_bg'], palette['fcitx5_hl_bg']
    bh, bs, bl = hex_to_hsl(bg)
    border = hsl_to_hex(bh, bs, min(bl + 5, 100))
    hh, hs, hl_val = hex_to_hsl(hl)
    hborder = hsl_to_hex(hh, hs, min(hl_val + 5, 100))
    
    panel_svg = f'<svg xmlns="http://www.w3.org/2000/svg" width="40" height="100"><g><rect width="39" height="99" x=".5" y=".5" fill="{bg}" stroke="{border}" rx="10" ry="10"/></g></svg>'
    highlight_svg = f'<svg xmlns="http://www.w3.org/2000/svg" width="39" height="44"><g><rect width="39" height="44" x="0" y="0" fill="{hl}" stroke="{hborder}" stroke-width="0" rx="8" ry="8"/></g></svg>'
    
    with open(theme_dir / "panel.svg", "w") as f: f.write(panel_svg)
    with open(theme_dir / "highlight.svg", "w") as f: f.write(highlight_svg)
    
    theme = f"""[Metadata]
Name=morandi
Version=0.0.3
Author=morandi-gen
Description=Auto-generated Morandi theme

[InputPanel]
NormalColor={palette['fcitx5_text']}
HighlightColor={palette['fcitx5_hl_text']}
HighlightBackgroundColor={palette['fcitx5_hl_bg']}
HighlightCandidateColor={palette['fcitx5_text']}
EnableBlur=True
FullWidthHighlight=True
PageButtonAlignment=Bottom
[InputPanel/BlurMargin]
Left=0\nRight=0\nTop=0\nBottom=0
[InputPanel/Background]
Image=panel.svg
Color={palette['fcitx5_bg']}
BorderColor={palette['fcitx5_bg']}
BorderWidth=0
[InputPanel/Background/Margin]
Left=6\nRight=6\nTop=6\nBottom=6
[InputPanel/Highlight]
Image=highlight.svg
Color={palette['fcitx5_hl_bg']}
BorderColor={palette['fcitx5_hl_bg']}00
BorderWidth=0
[InputPanel/Highlight/Margin]
Left=4\nRight=4\nTop=3\nBottom=3
[InputPanel/TextMargin]
Left=8\nRight=8\nTop=4\nBottom=4
[Menu]
NormalColor={palette['fcitx5_text']}
HighlightCandidateColor={palette['fcitx5_text']}
Spacing=0
[Menu/Background]
Image=panel.svg
Color={palette['fcitx5_bg']}
BorderColor={palette['fcitx5_bg']}00
BorderWidth=0
[Menu/Background/Margin]
Left=4\nRight=4\nTop=4\nBottom=4
[Menu/Highlight]
Image=highlight.svg
Color={palette['fcitx5_hl_bg']}
BorderColor={palette['fcitx5_hl_bg']}00
BorderWidth=0
[Menu/Highlight/Margin]
Left=2\nRight=2\nTop=1\nBottom=1
[Menu/Separator]
Color={palette['fcitx5_bg_alt']}
BorderColor={palette['fcitx5_bg_alt']}00
BorderWidth=0
"""
    with open(FCITX5_THEME, "w") as f: f.write(theme)
    classicui = Path.home() / ".config/fcitx5/conf/classicui.conf"
    if classicui.exists():
        content = classicui.read_text()
        content = re.sub(r"^Theme=.*", "Theme=morandi", content, flags=re.MULTILINE)
        content = re.sub(r"^DarkTheme=.*", "DarkTheme=morandi", content, flags=re.MULTILINE)
        content = re.sub(r"^UseDarkTheme=.*", "UseDarkTheme=False", content, flags=re.MULTILINE)
        content = re.sub(r"^TrayOutlineColor=.*", f"TrayOutlineColor={tray_outline}", content, flags=re.MULTILINE)
        content = re.sub(r"^TrayTextColor=.*", f"TrayTextColor={tray_text}", content, flags=re.MULTILINE)
        classicui.write_text(content)

def write_fastfetch(palette):
    config = f"""{{
    "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
    "logo": {{ "type": "chafa", "source": "{Path.home()}/.config/fastfetch/avatar.png", "width": 40, "height": 19, "padding": {{ "top": 2, "right": 2 }} }},
    "display": {{ "separator": "  ", "disableLinewrap": true, "color": {{ "keys": "{palette['iris']}", "title": "{palette['text']}" }} }},
    "modules": [ "title", "separator", {{ "type": "os", "key": " \uf30e OS" }}, {{ "type": "kernel", "key": " \uf331 Kernel" }}, {{ "type": "uptime", "key": " \uf017 Uptime" }}, {{ "type": "packages", "key": " \uf2dc Packages" }}, {{ "type": "shell", "key": " \uf489 Shell" }}, {{ "type": "terminal", "key": " \uf120 Terminal" }}, {{ "type": "de", "key": " \uf35e DE" }}, {{ "type": "wm", "key": " \uf2d2 WM" }}, "separator", {{ "type": "host", "key": " \uf2db Host" }}, {{ "type": "cpu", "key": " \uf2db CPU" }}, {{ "type": "gpu", "key": " \uf26c GPU" }}, {{ "type": "memory", "key": " \uf0e4 Memory" }}, "colors" ]
}}"""
    FASTFETCH_CONFIG.write_text(config)

ALACRITTY_ORIGINAL_NORMAL = {"black": "#1c1c1c", "red": "#ff6c6b", "green": "#98be65", "yellow": "#ecbe7b", "blue": "#51afef", "magenta": "#c678dd", "cyan": "#46d9ff", "white": "#bbc2cf"}
ALACRITTY_ORIGINAL_BRIGHT = {"black": "#5b6268", "red": "#da8548", "green": "#4db5bd", "yellow": "#ecbe7b", "blue": "#3071db", "magenta": "#a9a1e1", "cyan": "#46d9ff", "white": "#dfdfdf"}

def write_alacritty():
    if not ALACRITTY_TOML.exists(): return
    content = ALACRITTY_TOML.read_text()
    normal_colors = "\n".join(f'{k} = "{morandi(v, 0.45, -5, 0, 40)}"' for k, v in ALACRITTY_ORIGINAL_NORMAL.items())
    bright_colors = "\n".join(f'{k} = "{morandi(v, 0.45, -5, 0, 40)}"' for k, v in ALACRITTY_ORIGINAL_BRIGHT.items())
    content = re.sub(r"\[colors\.normal\]\n(.*?\n)+?(?=\[colors\.bright\])", f"[colors.normal]\n{normal_colors}\n", content, flags=re.MULTILINE)
    content = re.sub(r"\[colors\.bright\]\n(.*?\n)+?(?=\[colors\.cursor\])", f"[colors.bright]\n{bright_colors}\n", content, flags=re.MULTILINE)
    ALACRITTY_TOML.write_text(content)

def hex_to_rgb(hex_color):
    h = hex_color.lstrip("#")
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)

def _replace_jsonc_block(content, key, new_block):
    """Replace a top-level key's value block in JSONC, handling nested braces/brackets.
    If the key doesn't exist, insert it before the final closing brace of the root object."""
    pattern = re.compile(r'(\s*"' + re.escape(key) + r'"\s*:\s*)')
    m = pattern.search(content)
    if m:
        # Find the opening brace or bracket after the key
        opener_pos = m.end()
        while opener_pos < len(content) and content[opener_pos] in " \t\n\r":
            opener_pos += 1
        if opener_pos >= len(content):
            return content
        opener = content[opener_pos]
        closer = "}" if opener == "{" else "]"
        depth, end = 0, opener_pos
        for i in range(opener_pos, len(content)):
            if content[i] == opener:
                depth += 1
            elif content[i] == closer:
                depth -= 1
                if depth == 0:
                    end = i + 1
                    break
        if isinstance(new_block, list):
            new_json = json.dumps(new_block, indent=4)
        else:
            new_json = json.dumps(new_block, indent=4)
        new_json = re.sub(r"\n", "\n    ", new_json)
        return content[:m.start()] + f'\n    "{key}": {new_json}' + content[end:]
    else:
        # Insert before the last closing brace of the root object
        if isinstance(new_block, list):
            new_json = json.dumps(new_block, indent=4)
        else:
            new_json = json.dumps(new_block, indent=4)
        new_json = re.sub(r"\n", "\n    ", new_json)
        insert_block = f'    "{key}": {new_json}'
        last_brace = content.rfind("}")
        if last_brace != -1:
            before = content[:last_brace].rstrip()
            if before and not before.endswith(","):
                before += ","
            return before + "\n" + insert_block + "\n" + content[last_brace:]
        return content


def write_vscode(palette):
    if not VSCODE_SETTINGS.exists():
        return

    p = palette
    # Syntax palette synced to Neovim morandi theme — uses _light variants for soft contrast
    syntax = {
        "comment":              "#706e66",
        "keyword":              "#d47a7e",
        "keyword.control":      "#d47a7e",
        "keyword.operator":     "#dededd",
        "storage":              "#d47a7e",
        "storage.type":         "#d5cfb2",
        "entity.name.function": "#c4c4b7",
        "entity.name.type":     "#d5cfb2",
        "entity.name.class":    "#d5cfb2",
        "entity.name.tag":      "#c4c4b7",
        "entity.other":         "#f2f2f2",
        "variable":             "#f2f2f2",
        "variable.parameter":   "#dededd",
        "variable.language":    "#c5c2b2",
        "string":               "#c0c3b8",
        "string.regexp":        "#d06a7a",
        "string.escape":        "#d4907e",
        "constant.numeric":     "#d4907e",
        "constant.language":    "#d5cfb2",
        "support.type":         "#d5cfb2",
        "support.function":     "#c4c4b7",
        "entity.other.attribute": "#c4c4b7",
        "punctuation":          "#706e66",
        "punctuation.definition": "#706e66",
        "meta.decorator":       "#c5c2b2",
        "markup.heading":       "#d47a7e",
        "markup.italic":        "#dededd",
        "markup.bold":          "#f2f2f2",
        "markup.inline.raw":    "#c0c3b8",
        "markup.deleted":       "#d06a7a",
        "markup.inserted":      "#c0c3b8",
        "markup.changed":       "#d4907e"
    }

    colors = {
        # Activity bar
        "activityBar.background":                            "#00000000",
        "activityBar.foreground":                            p["iris"],
        "activityBar.activeBorder":                          p["iris"],
        "activityBarBadge.background":                       p["iris"],
        "activityBarBadge.foreground":                       p["mantle"],
        "activityBar.activeBackground":                      p["surface0"] + "80",
        "activityBar.border":                                p["surface1"],

        # Side bar
        "sideBar.background":                                "#00000000",
        "sideBar.foreground":                                p["text"],
        "sideBar.border":                                    p["surface1"],
        "sideBarTitle.foreground":                           p["text"],
        "sideBarSectionHeader.background":                   p["surface0"],
        "sideBarSectionHeader.foreground":                   p["subtext1"],
        "sideBarSectionHeader.border":                       p["surface1"],

        # Lists / tree
        "list.activeSelectionBackground":                    p["surface2"],
        "list.activeSelectionForeground":                    p["text"],
        "list.activeSelectionBorder":                        p["iris"],
        "list.inactiveSelectionBackground":                  p["surface1"],
        "list.inactiveSelectionForeground":                  p["text"],
        "list.hoverBackground":                              p["surface1"],
        "list.hoverForeground":                              p["text"],
        "list.focusBackground":                              p["surface0"],
        "list.focusForeground":                              p["text"],
        "list.focusBorder":                                  p["iris"] + "80",
        "list.highlightForeground":                          p["iris"],
        "list.errorForeground":                              p["love"],
        "list.warningForeground":                            "#d4907e",
        "listFilterWidget.background":                       p["surface0"],
        "listFilterWidget.outline":                          p["iris"],
        "listFilterWidget.noMatchesOutline":                 p["love"],
        "tree.indentGuidesStroke":                           p["surface1"],
        "tree.tableColumnsBorder":                           p["surface1"],

        # Editor
        "editor.background":                                 "#00000000",
        "editor.foreground":                                 p["text"],
        "editorLineNumber.foreground":                       p["overlay0"],
        "editorLineNumber.activeForeground":                 p["subtext1"],
        "editor.lineHighlightBackground":                    p["surface0"] + "40",
        "editor.lineHighlightBorder":                        "#00000000",
        "editor.selectionBackground":                        p["surface2"] + "80",
        "editor.selectionHighlightBackground":               p["surface1"] + "40",
        "editor.selectionHighlightBorder":                   p["surface1"] + "60",
        "editor.wordHighlightBackground":                    p["surface1"] + "40",
        "editor.wordHighlightBorder":                        p["surface1"] + "60",
        "editor.wordHighlightStrongBackground":              p["surface2"] + "50",
        "editor.findMatchBackground":                        p["iris"] + "60",
        "editor.findMatchBorder":                            p["iris"],
        "editor.findMatchHighlightBackground":               "#d4907e30",
        "editor.findMatchHighlightBorder":                   "#d4907e50",
        "editor.findRangeHighlightBackground":               p["surface1"] + "30",
        "editor.rangeHighlightBackground":                   p["surface0"] + "30",
        "editor.hoverHighlightBackground":                   p["surface1"] + "40",
        "editorCursor.foreground":                           p["iris"],
        "editorCursor.background":                           p["mantle"],
        "editorIndentGuide.background1":                     p["surface1"] + "80",
        "editorIndentGuide.background2":                     p["surface1"] + "40",
        "editorIndentGuide.activeBackground1":               p["overlay0"],
        "editorIndentGuide.activeBackground2":               p["overlay1"],
        "editorRuler.foreground":                            p["surface1"],
        "editorBracketMatch.background":                     p["surface2"] + "40",
        "editorBracketMatch.border":                         p["iris"] + "80",
        "editorBracketHighlight.foreground1":                 p["iris"],
        "editorBracketHighlight.foreground2":                 p["foam"],
        "editorBracketHighlight.foreground3":                 "#d4907e",
        "editorBracketHighlight.foreground4":                 "#d5cfb2",
        "editorBracketHighlight.foreground5":                 p["rose"],
        "editorBracketHighlight.foreground6":                 "#c0c3b8",
        "editorGutter.background":                           "#00000000",
        "editorOverviewRuler.border":                        "#00000000",
        "editorError.foreground":                            p["love"],
        "editorWarning.foreground":                          "#d4907e",
        "editorInfo.foreground":                             "#d5cfb2",
        "editorHint.foreground":                             "#c0c3b8",
        "editorWidget.background":                           p["surface0"],
        "editorWidget.foreground":                           p["text"],
        "editorWidget.border":                               p["surface1"],
        "editorWidget.resizeBorder":                         p["iris"],
        "editorSuggestWidget.background":                    p["surface0"],
        "editorSuggestWidget.border":                        p["surface1"],
        "editorSuggestWidget.foreground":                    p["text"],
        "editorSuggestWidget.selectedBackground":             p["surface2"],
        "editorSuggestWidget.selectedForeground":             p["text"],
        "editorSuggestWidget.focusHighlightForeground":       p["iris"],
        "editorSuggestWidget.highlightForeground":            p["iris"],
        "editorHoverWidget.background":                      p["surface0"],
        "editorHoverWidget.border":                          p["surface1"],
        "editorHoverWidget.foreground":                      p["text"],
        "editorHoverWidget.highlightForeground":              p["iris"],
        "editorHoverWidget.statusBarBackground":              p["surface0"],
        "editorStickyScroll.hoverBackground":                p["surface1"],
        "editorInlayHint.background":                        p["surface0"] + "C0",
        "editorInlayHint.foreground":                        p["overlay1"],
        "editorInlayHint.typeForeground":                    "#d5cfb2",
        "editorInlayHint.parameterForeground":               "#d4907e",
        "editorInlayHint.textForeground":                    p["overlay1"],
        "editorGhostText.background":                        p["surface0"] + "80",
        "editorGhostText.foreground":                        p["overlay1"],
        "editorGhostText.border":                            p["surface1"],
        "editor.foldBackground":                             p["surface0"] + "40",

        # Editor groups & tabs
        "editorGroupHeader.tabsBackground":                  "#00000000",
        "editorGroupHeader.noTabsBackground":                "#00000000",
        "editorGroupHeader.border":                          p["surface1"],
        "editorGroupHeader.tabsBorder":                      p["surface1"],
        "editorGroup.border":                                p["surface1"],
        "editorGroup.dropBackground":                        p["iris"] + "20",

        "tab.activeBackground":                              "#00000000",
        "tab.activeForeground":                              p["text"],
        "tab.activeBorderTop":                               p["iris"],
        "tab.activeBorder":                                  "#00000000",
        "tab.inactiveBackground":                            "#00000000",
        "tab.inactiveForeground":                            p["subtext0"],
        "tab.border":                                        p["surface0"],
        "tab.hoverBackground":                               p["surface0"],
        "tab.hoverBorder":                                   p["iris"],
        "tab.unfocusedActiveBackground":                     "#00000000",
        "tab.unfocusedActiveForeground":                     p["subtext1"],
        "tab.unfocusedInactiveBackground":                   "#00000000",
        "tab.unfocusedInactiveForeground":                   p["subtext0"],
        "tab.lastPinnedBorder":                              p["iris"] + "80",
        "tab.lastPinnedBorderActive":                        p["iris"],
        "tab.activeModifiedBorder":                          "#d4907e",
        "tab.inactiveModifiedBorder":                        "#d4907e" + "80",

        # Terminal
        "terminal.background":                               p["mantle"],
        "terminal.foreground":                               p["text"],
        "terminal.border":                                   p["surface1"],
        "terminal.ansiBlack":                                p["mantle"],
        "terminal.ansiRed":                                  p["love"],
        "terminal.ansiGreen":                                "#c0c3b8",
        "terminal.ansiYellow":                               "#d4907e",
        "terminal.ansiBlue":                                 p["iris"],
        "terminal.ansiMagenta":                              p["rose"],
        "terminal.ansiCyan":                                 p["sky"],
        "terminal.ansiWhite":                                p["text"],
        "terminal.ansiBrightBlack":                          p["surface1"],
        "terminal.ansiBrightRed":                            p["love"],
        "terminal.ansiBrightGreen":                          "#c0c3b8",
        "terminal.ansiBrightYellow":                         "#d4907e",
        "terminal.ansiBrightBlue":                           p["iris"],
        "terminal.ansiBrightMagenta":                        p["rose"],
        "terminal.ansiBrightCyan":                           p["sky"],
        "terminal.ansiBrightWhite":                          p["text"],
        "terminal.tab.activeBorder":                         p["iris"],
        "terminal.overviewRulerBorder":                      "#00000000",
        "terminalCommandDecoration.defaultBackground":        p["surface1"],
        "terminalCommandDecoration.successBackground":        "#c0c3b8" + "40",
        "terminalCommandDecoration.errorBackground":          p["love"] + "40",
        "terminalCommandDecoration.warningBackground":        "#d4907e" + "40",
        "terminal.selectionBackground":                       p["surface2"] + "80",
        "terminalCursor.foreground":                          p["iris"],

        # Status bar
        "statusBar.background":                              p["mantle"],
        "statusBar.foreground":                              p["subtext1"],
        "statusBar.border":                                  p["surface1"],
        "statusBar.debuggingBackground":                     "#d4907e",
        "statusBar.debuggingForeground":                     p["mantle"],
        "statusBar.debuggingBorder":                         "#d4907e",
        "statusBar.noFolderBackground":                      p["surface0"],
        "statusBar.noFolderForeground":                      p["subtext1"],
        "statusBar.noFolderBorder":                          p["surface1"],
        "statusBar.itemsWarningForeground":                  "#d4907e",
        "statusBar.remoteBackground":                        p["iris"],
        "statusBar.remoteForeground":                        p["mantle"],
        "statusBar.remoteBorder":                            p["iris"],

        # Panel
        "panel.background":                                  "#00000000",
        "panel.border":                                      p["surface1"],
        "panelTitle.activeBorder":                           p["iris"],
        "panelTitle.activeForeground":                       p["text"],
        "panelTitle.inactiveForeground":                     p["subtext0"],
        "panelTitle.border":                                 "#00000000",
        "panel.dropBorder":                                  p["iris"],
        "panelInput.border":                                 p["surface1"],

        # Title bar
        "titleBar.activeBackground":                         p["mantle"],
        "titleBar.activeForeground":                         p["subtext1"],
        "titleBar.border":                                   "#00000000",
        "titleBar.inactiveBackground":                       p["mantle"],
        "titleBar.inactiveForeground":                       p["subtext0"],

        # Menu
        "menu.background":                                   p["surface0"],
        "menu.foreground":                                   p["text"],
        "menu.selectionBackground":                          p["surface2"],
        "menu.selectionForeground":                          p["text"],
        "menu.selectionBorder":                              p["iris"],
        "menu.separatorBackground":                          p["surface1"],
        "menu.border":                                       p["surface1"],
        "menubar.selectionBackground":                       p["surface1"],
        "menubar.selectionForeground":                       p["text"],
        "menubar.selectionBorder":                           p["iris"],

        # Input
        "input.background":                                  p["surface0"],
        "input.foreground":                                  p["text"],
        "input.border":                                      p["surface1"],
        "input.placeholderForeground":                       p["overlay1"],
        "inputOption.activeBorder":                          p["iris"],
        "inputOption.activeBackground":                      p["iris"] + "20",
        "inputOption.activeForeground":                      p["text"],
        "inputOption.hoverBackground":                       p["surface1"],
        "inputValidation.background":                        p["surface0"],
        "inputValidation.errorBackground":                   p["love"] + "30",
        "inputValidation.errorBorder":                       p["love"],
        "inputValidation.warningBackground":                 "#d4907e30",
        "inputValidation.warningBorder":                     "#d4907e",

        # Button
        "button.background":                                 p["iris"],
        "button.foreground":                                 p["mantle"],
        "button.hoverBackground":                            p["foam"],
        "button.secondaryBackground":                        p["surface1"],
        "button.secondaryForeground":                        p["text"],
        "button.secondaryHoverBackground":                   p["surface2"],
        "button.separator":                                  "#00000030",

        # Dropdown
        "dropdown.background":                               p["surface0"],
        "dropdown.foreground":                               p["text"],
        "dropdown.border":                                   p["surface1"],

        # Scrollbar
        "scrollbar.shadow":                                  "#00000030",
        "scrollbarSlider.background":                        p["surface1"] + "80",
        "scrollbarSlider.hoverBackground":                   p["surface2"],
        "scrollbarSlider.activeBackground":                  p["overlay0"],
        "scrollbarSlider.border":                            "transparent",

        # Badge
        "badge.background":                                  p["iris"],
        "badge.foreground":                                  p["mantle"],
        "badge.badgeForeground":                             p["text"],

        # Progress bar
        "progressBar.background":                            p["iris"],

        # Breadcrumb
        "breadcrumb.foreground":                             p["subtext0"],
        "breadcrumb.focusForeground":                        p["text"],
        "breadcrumbPicker.background":                       p["surface0"],
        "breadcrumbPicker.border":                           p["surface1"],
        "breadcrumb.focusBorder":                            p["iris"] + "80",

        # Git decorations
        "gitDecoration.modifiedResourceForeground":           "#d4907e",
        "gitDecoration.deletedResourceForeground":            p["love"],
        "gitDecoration.untrackedResourceForeground":           "#c0c3b8",
        "gitDecoration.ignoredResourceForeground":            p["subtext0"],
        "gitDecoration.conflictingResourceForeground":         p["rose"],
        "gitDecoration.stageModifiedResourceForeground":       "#d4907e",
        "gitDecoration.stageDeletedResourceForeground":        p["love"],
        "gitDecoration.renamedResourceForeground":            p["foam"],
        "gitDecoration.stageRenamedResourceForeground":        p["foam"],
        "gitDecoration.worktreeModifiedResourceForeground":    "#d4907e",
        "gitDecoration.worktreeDeletedResourceForeground":     p["love"],
        "gitDecoration.worktreeUntrackedResourceForeground":   "#c0c3b8",

        # Minimap
        "minimap.background":                                "#00000066",
        "minimap.foregroundOpacity":                         "0.7",
        "minimap.selectionHighlight":                         p["iris"] + "60",
        "minimap.selectionHighlightBorder":                   p["iris"],
        "minimap.findMatchHighlight":                         p["iris"] + "50",
        "minimap.errorHighlight":                             p["love"] + "60",
        "minimapGutter.addedBackground":                      "#c0c3b8",
        "minimapGutter.modifiedBackground":                   "#d4907e",
        "minimapGutter.deletedBackground":                    p["love"],

        # Peek view
        "peekView.border":                                   p["iris"],
        "peekViewEditor.background":                         p["surface0"],
        "peekViewEditor.gutterBackground":                   p["surface0"],
        "peekViewResult.background":                         p["mantle"],
        "peekViewResult.fileForeground":                     p["text"],
        "peekViewResult.lineForeground":                     p["subtext0"],
        "peekViewResult.selectionBackground":                p["surface2"],
        "peekViewResult.selectionForeground":                p["text"],
        "peekViewResult.matchHighlightBackground":            p["iris"] + "40",
        "peekViewResult.matchHighlightForeground":            p["text"],
        "peekViewResult.wordHighlightBackground":             p["surface1"] + "40",
        "peekViewResult.wordHighlightForeground":             p["text"],
        "peekViewTitle.background":                          p["surface0"],
        "peekViewTitle.label.foreground":                    p["text"],
        "peekViewTitle.description.foreground":               p["subtext0"],
        "peekViewEditor.matchHighlightBackground":            p["iris"] + "40",
        "peekViewEditor.matchHighlightForeground":            p["text"],
        "peekViewEditor.wordHighlightBackground":             p["surface1"] + "40",
        "peekViewEditor.wordHighlightForeground":             p["text"],
        "peekViewEditorCursor.foreground":                    p["iris"],

        # Focus & borders
        "focusBorder":                                       p["iris"] + "80",
        "contrastBorder":                                    "#00000000",
        "contrastActiveBorder":                              "#00000000",
        "widget.shadow":                                     "#00000040",
        "widget.border":                                     p["surface1"],

        # Quick input / command palette
        "quickInput.background":                              p["surface0"],
        "quickInput.foreground":                              p["text"],
        "quickInputList.focusBackground":                     p["surface1"],
        "quickInputList.focusForeground":                     p["text"],
        "quickInputList.focusBorder":                         p["iris"] + "80",
        "quickInputTitle.background":                         p["surface0"],

        # Keybinding label
        "keybindingLabel.background":                         p["surface0"],
        "keybindingLabel.foreground":                         p["text"],
        "keybindingLabel.border":                             p["surface1"],
        "keybindingLabel.bottomBorder":                       p["overlay0"],
        "keybindingLabel.activeBackground":                   p["surface1"],
        "keybindingLabel.activeForeground":                   p["text"],
        "keybindingLabel.activeBorder":                       p["iris"],
        "keybindingLabel.activeBottomBorder":                 p["iris"],
        "keybindingLabel.hoverBackground":                    p["surface1"],
        "keybindingLabel.hoverForeground":                    p["text"],
        "keybindingLabel.hoverBorder":                        p["iris"],
        "keybindingLabel.hoverBottomBorder":                  p["iris"],

        # Command center (title bar)
        "commandCenter.foreground":                           p["subtext1"],
        "commandCenter.activeForeground":                     p["text"],
        "commandCenter.background":                           p["surface0"],
        "commandCenter.activeBackground":                     p["surface1"],
        "commandCenter.border":                               p["surface1"],
        "commandCenter.activeBorder":                         p["iris"],
        "commandCenter.hoverBackground":                      p["surface1"],
        "commandCenter.hoverForeground":                      p["text"],
        "commandCenter.hoverBorder":                          p["iris"],
        "commandCenter.foregroundBorder":                     p["surface1"],
        "commandCenter.activeForegroundBorder":               p["iris"],

        # Settings
        "settings.headerForeground":                          p["text"],
        "settings.modifiedItemIndicator":                      p["iris"],
        "settings.focusedRowBackground":                       p["surface0"],
        "settings.headerBorder":                              p["surface1"],
        "settings.tabHoverBackground":                         p["surface1"],
        "settings.checkboxBackground":                          p["surface0"],
        "settings.checkboxForeground":                          p["text"],
        "settings.checkboxBorder":                              p["surface1"],
        "settings.focusedRowBorder":                           p["iris"],
        "settings.rowHoverBackground":                          p["surface1"],
        "settings.textLinkForeground":                          p["iris"],

        # Welcome page
        "welcomePage.background":                              p["base"],
        "welcomePage.tileBackground":                          p["surface0"],
        "welcomePage.tileBorder":                              p["surface1"],
        "welcomePage.progress.foreground":                     p["iris"],
        "walkThrough.embeddedEditorBackground":                p["surface0"],
        "walkThrough.embeddedEditorBorder":                    p["surface1"],

        # Diff editor
        "diffEditor.insertedTextBackground":                   "#c0c3b820",
        "diffEditor.insertedTextBorder":                       "#c0c3b840",
        "diffEditor.removedTextBackground":                    p["love"] + "20",
        "diffEditor.removedTextBorder":                        p["love"] + "40",
        "diffEditor.border":                                   p["surface1"],
        "diffEditor.insertedLineBackground":                   "#c0c3b815",
        "diffEditor.removedLineBackground":                    p["love"] + "15",
        "diffEditorGutter.insertedLineBackground":             "#c0c3b815",
        "diffEditorGutter.removedLineBackground":              p["love"] + "15",
        "diffEditor.diagnostic.deletedBackground":              p["love"],
        "diffEditor.diagnostic.modifiedBackground":             "#d4907e",

        # Debug toolbar & exception widget
        "debugToolBar.background":                             p["surface0"],
        "debugToolBar.border":                                 p["surface1"],
        "debugIcon.breakpointForeground":                       p["love"],
        "debugIcon.startForeground":                            "#c0c3b8",
        "debugIcon.pauseForeground":                            p["iris"],
        "debugIcon.stopForeground":                             p["love"],
        "debugIcon.restartForeground":                          "#c0c3b8",
        "debugIcon.stepOverForeground":                         p["iris"],
        "debugIcon.stepIntoForeground":                         p["iris"],
        "debugIcon.stepOutForeground":                          p["iris"],
        "debugIcon.stepBackForeground":                         p["iris"],
        "debugIcon.continueForeground":                         "#c0c3b8",
        "debugIcon.disconnectForeground":                       p["love"],
        "debugExceptionWidget.background":                      p["surface0"],
        "debugExceptionWidget.foreground":                      p["text"],
        "debugExceptionWidget.border":                          p["love"],

        # Notifications
        "notificationCenter.border":                           p["surface1"],
        "notificationCenterHeader.background":                  p["surface0"],
        "notificationCenterHeader.foreground":                  p["text"],
        "notifications.background":                             p["surface0"],
        "notifications.foreground":                             p["text"],
        "notifications.border":                                 p["surface1"],
        "notificationLink.foreground":                          p["iris"],
        "notificationsErrorIcon.foreground":                     p["love"],
        "notificationsWarningIcon.foreground":                   "#d4907e",
        "notificationsInfoIcon.foreground":                      "#d5cfb2",
        "notificationToast.border":                             p["surface1"],

        # Command palette search match
        "searchEditor.findMatchBackground":                     p["iris"] + "30",
        "searchEditor.findMatchBorder":                         p["iris"] + "60",
        "search.resultsInfoForeground":                         p["subtext0"],

        # Sticky scroll
        "editorStickyScroll.background":                       p["surface0"],
        "editorStickyScrollHover.background":                   p["surface1"],
        "editorStickyScroll.border":                            p["surface1"],

        # Editor overview ruler
        "editorOverviewRuler.findMatchForeground":               p["iris"] + "80",
        "editorOverviewRuler.findMatchHighlightForeground":       "#d4907e60",
        "editorOverviewRuler.errorForeground":                    p["love"],
        "editorOverviewRuler.warningForeground":                  "#d4907e",
        "editorOverviewRuler.infoForeground":                     "#d5cfb2",
        "editorOverviewRuler.bracketMatchForeground":             p["iris"] + "80",
        "editorOverviewRuler.selectionHighlightForeground":       p["surface2"],
        "editorOverviewRuler.wordHighlightForeground":            p["surface1"],
        "editorOverviewRuler.wordHighlightStrongForeground":      p["surface2"],
        "editorOverviewRuler.addedForeground":                    "#c0c3b880",
        "editorOverviewRuler.modifiedForeground":                 "#d4907e80",
        "editorOverviewRuler.deletedForeground":                  p["love"] + "80",

        # Breadcrumb
        "breadcrumb.activeSelectionForeground":                   p["iris"],

        # Toolbar
        "toolbar.hoverBackground":                               p["surface1"],
        "toolbar.activeBackground":                              p["surface2"]
    }

    token_colors = [
        {"scope": ["comment", "punctuation.definition.comment"], "settings": {"foreground": syntax["comment"], "fontStyle": "italic"}},
        {"scope": ["keyword", "keyword.control", "keyword.operator.new", "keyword.operator.expression"], "settings": {"foreground": syntax["keyword"], "fontStyle": "bold"}},
        {"scope": ["keyword.operator"], "settings": {"foreground": syntax["keyword.operator"], "fontStyle": ""}},
        {"scope": ["storage", "storage.type", "storage.modifier"], "settings": {"foreground": syntax["storage"], "fontStyle": "bold"}},
        {"scope": ["entity.name.function", "support.function", "meta.function-call"], "settings": {"foreground": syntax["entity.name.function"]}},
        {"scope": ["entity.name.type", "entity.name.class", "support.type", "support.class", "entity.other.inherited-class"], "settings": {"foreground": syntax["entity.name.type"], "fontStyle": "bold"}},
        {"scope": ["entity.name.tag", "punctuation.definition.tag"], "settings": {"foreground": syntax["entity.name.tag"]}},
        {"scope": ["entity.other.attribute-name"], "settings": {"foreground": syntax["entity.other.attribute"]}},
        {"scope": ["variable", "variable.other", "variable.other.readwrite", "variable.other.object"], "settings": {"foreground": syntax["variable"]}},
        {"scope": ["variable.parameter", "variable.other.readwrite", "meta.parameter"], "settings": {"foreground": syntax["variable.parameter"]}},
        {"scope": ["variable.language", "variable.language.this", "variable.language.super"], "settings": {"foreground": syntax["variable.language"]}},
        {"scope": ["string", "string.quoted", "string.template"], "settings": {"foreground": syntax["string"]}},
        {"scope": ["string.regexp"], "settings": {"foreground": syntax["string.regexp"]}},
        {"scope": ["constant.character.escape"], "settings": {"foreground": syntax["string.escape"]}},
        {"scope": ["constant.numeric", "constant.numeric.float", "constant.numeric.hex", "constant.numeric.integer"], "settings": {"foreground": syntax["constant.numeric"]}},
        {"scope": ["constant.language", "constant.language.null", "constant.language.boolean"], "settings": {"foreground": syntax["constant.language"]}},
        {"scope": ["support.type", "support.type.primitive"], "settings": {"foreground": syntax["support.type"]}},
        {"scope": ["punctuation", "punctuation.definition", "punctuation.separator", "punctuation.terminator", "punctuation.brackets", "punctuation.definition.variable", "punctuation.definition.parameters", "punctuation.definition.entity"], "settings": {"foreground": syntax["punctuation"]}},
        {"scope": ["meta.decorator", "punctuation.decorator"], "settings": {"foreground": syntax["meta.decorator"]}},
        {"scope": ["markup.heading", "entity.name.section"], "settings": {"foreground": syntax["markup.heading"], "fontStyle": "bold"}},
        {"scope": ["markup.italic"], "settings": {"fontStyle": "italic", "foreground": syntax["markup.italic"]}},
        {"scope": ["markup.bold"], "settings": {"fontStyle": "bold", "foreground": syntax["markup.bold"]}},
        {"scope": ["markup.inline.raw", "markup.fenced_code"], "settings": {"foreground": syntax["markup.inline.raw"]}},
        {"scope": ["markup.deleted"], "settings": {"foreground": syntax["markup.deleted"]}},
        {"scope": ["markup.inserted"], "settings": {"foreground": syntax["markup.inserted"]}},
        {"scope": ["markup.changed"], "settings": {"foreground": syntax["markup.changed"]}},
        {"scope": ["entity.name.label", "entity.name.namespace", "entity.name.module"], "settings": {"foreground": p["text"]}},
        {"scope": ["entity.name.namespace", "entity.name.module"], "settings": {"foreground": p["iris"]}},
        {"scope": ["punctuation.definition.block", "punctuation.definition.parameters.begin", "punctuation.definition.parameters.end"], "settings": {"foreground": p["overlay0"]}},
        # Python
        {"scope": ["keyword.control.flow.python", "keyword.control.import.python", "keyword.control.from.python"], "settings": {"foreground": syntax["keyword"]}},
        {"scope": ["variable.parameter.function.language.python", "meta.function-call.arguments.python"], "settings": {"foreground": syntax["variable.parameter"]}},
        {"scope": ["string.quoted.docstring", "string.quoted.docstring.python"], "settings": {"foreground": syntax["comment"], "fontStyle": "italic"}},
        {"scope": ["support.function.builtin.python"], "settings": {"foreground": syntax["support.function"]}},
        {"scope": ["entity.name.function.decorator.python", "meta.function.decorator.python"], "settings": {"foreground": syntax["meta.decorator"]}},
        # JavaScript / TypeScript
        {"scope": ["entity.name.type.numeric.ts", "entity.name.type.numeric.tsx"], "settings": {"foreground": syntax["constant.numeric"]}},
        {"scope": ["variable.parameter.ts", "variable.parameter.tsx", "meta.parameter.ts", "meta.parameter.tsx"], "settings": {"foreground": syntax["variable.parameter"]}},
        {"scope": ["support.type.primitive.ts", "support.type.primitive.tsx", "support.type.builtin.ts", "support.type.builtin.tsx"], "settings": {"foreground": syntax["support.type"]}},
        {"scope": ["variable.other.constant.ts", "variable.other.constant.tsx", "variable.other.readwrite.alias.ts", "variable.other.readwrite.alias.tsx"], "settings": {"foreground": syntax["variable"]}},
        {"scope": ["entity.name.function.tagged-template", "support.function.property-access"], "settings": {"foreground": syntax["support.function"]}},
        # C / C++
        {"scope": ["entity.name.function.c", "entity.name.function.cpp"], "settings": {"foreground": syntax["entity.name.function"]}},
        {"scope": ["support.type.sys-types.c", "support.type.sys-types.cpp"], "settings": {"foreground": syntax["support.type"]}},
        # CSS
        {"scope": ["entity.name.tag.css", "entity.other.attribute-name.class.css", "entity.other.attribute-name.id.css"], "settings": {"foreground": syntax["entity.name.tag"]}},
        {"scope": ["support.type.property-name.css"], "settings": {"foreground": syntax["entity.other.attribute"]}},
        # Rust
        {"scope": ["entity.name.lifetime.rust"], "settings": {"foreground": syntax["variable.language"]}},
        {"scope": ["storage.modifier.lifetime.rust", "punctuation.definition.lifetime.rust"], "settings": {"foreground": syntax["variable.language"]}},
        # Go
        {"scope": ["storage.type.other.go", "storage.type.builtin.go"], "settings": {"foreground": syntax["support.type"]}},
        # Lua
        {"scope": ["keyword.operator.logical.lua"], "settings": {"foreground": syntax["keyword"]}},
        # Git
        {"scope": ["comment.line.double-slash.jsdoc", "comment.block.documentation"], "settings": {"foreground": syntax["comment"], "fontStyle": "italic"}}
    ]

    content = VSCODE_SETTINGS.read_text()
    content = _replace_jsonc_block(content, "workbench.colorCustomizations", colors)
    content = _replace_jsonc_block(content, "editor.tokenColorCustomizations", token_colors)
    VSCODE_SETTINGS.write_text(content)

def write_kde(colors):
    def rgb_str(c): return f"{c[0]},{c[1]},{c[2]}"
    bg, surface, surface_var = hex_to_rgb(colors["background"]), hex_to_rgb(colors["surface_container"]), hex_to_rgb(colors["surface_variant"])
    primary, primary_cont = hex_to_rgb(colors["primary"]), hex_to_rgb(colors["primary_container"])
    on_surface, on_surface_var, on_primary = hex_to_rgb(colors["on_surface"]), hex_to_rgb(colors["on_surface_variant"]), hex_to_rgb(colors["on_primary"])
    error, window_bg = hex_to_rgb(colors["error"]), hex_to_rgb(colors["surface_container_low"])
    content = f"""[General]\nName=Morandi Dark\nshadeSortColumn=true\n
[Colors:Button]
BackgroundNormal={rgb_str(surface)}\nBackgroundAlternate={rgb_str(surface)}
ForegroundNormal={rgb_str(on_surface)}\nForegroundInactive={rgb_str(on_surface_var)}
ForegroundActive={rgb_str(primary)}\nForegroundLink={rgb_str(primary)}\nForegroundNegative={rgb_str(error)}
DecorationFocus={rgb_str(primary_cont)}\nDecorationHover={rgb_str(primary)}
[Colors:View]
BackgroundNormal={rgb_str(bg)}\nBackgroundAlternate={rgb_str(surface_var)}
ForegroundNormal={rgb_str(on_surface)}\nForegroundInactive={rgb_str(on_surface_var)}
ForegroundActive={rgb_str(primary)}\nForegroundLink={rgb_str(primary)}\nForegroundNegative={rgb_str(error)}
DecorationFocus={rgb_str(primary_cont)}\nDecorationHover={rgb_str(primary)}
[Colors:Window]
BackgroundNormal={rgb_str(window_bg)}\nBackgroundAlternate={rgb_str(window_bg)}
ForegroundNormal={rgb_str(on_surface)}\nForegroundInactive={rgb_str(on_surface_var)}
ForegroundActive={rgb_str(primary)}\nForegroundLink={rgb_str(primary)}\nForegroundNegative={rgb_str(error)}
DecorationFocus={rgb_str(primary_cont)}\nDecorationHover={rgb_str(primary)}
[Colors:Selection]
BackgroundNormal={rgb_str(primary_cont)}\nBackgroundAlternate={rgb_str(primary_cont)}
ForegroundNormal={rgb_str(on_primary)}\nForegroundInactive={rgb_str(on_primary)}\nForegroundActive={rgb_str(on_primary)}
ForegroundLink={rgb_str(on_primary)}\nForegroundNegative={rgb_str(error)}
DecorationFocus={rgb_str(primary_cont)}\nDecorationHover={rgb_str(primary)}
[WM]
activeBackground={rgb_str(surface)}\nactiveForeground={rgb_str(on_surface)}
inactiveBackground={rgb_str(bg)}\ninactiveForeground={rgb_str(on_surface_var)}
activeTitleBtnBg={rgb_str(primary_cont)}\ninactiveTitleBtnBg={rgb_str(surface)}\n"""
    KDE_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    KDE_OUTPUT.write_text(content)

def write_blender(palette):
    script_content = f"""import bpy
theme = bpy.context.preferences.themes[0]
theme.name = "Morandi"
def h(hx): return [int(hx.lstrip('#')[i:i+2], 16)/255.0 for i in (0, 2, 4)]
bg, fg, accent, bg_light, bg_dark = h('{palette['base']}'), h('{palette['text']}'), h('{palette['iris']}'), h('{palette['surface0']}'), h('{palette['mantle']}')
def s(o, a, c):
    try: setattr(o, a, tuple(c + [1.0]) if len(getattr(o, a)) == 4 else tuple(c))
    except: pass
spaces = [getattr(theme, n).space if hasattr(getattr(theme, n), 'space') else getattr(theme, n) for n in dir(theme) if not n.startswith('_') and (hasattr(getattr(theme, n), 'space') or hasattr(getattr(theme, n), 'back'))]
for sp in spaces:
    if hasattr(sp, 'back'): s(sp, 'back', bg)
    if hasattr(sp, 'text'): s(sp, 'text', fg)
    if hasattr(sp, 'header'): s(sp, 'header', bg)
    if hasattr(sp, 'header_text'): s(sp, 'header_text', fg)
    if hasattr(sp, 'panelcolors'):
        s(sp.panelcolors, 'header', bg_light); s(sp.panelcolors, 'back', bg)
v3 = theme.view_3d
if hasattr(v3, 'space') and hasattr(v3.space, 'gradients'): s(v3.space.gradients, 'high_gradient', bg)
ui = theme.user_interface
for w in [ui.wcol_regular, ui.wcol_tool, ui.wcol_text, ui.wcol_option, ui.wcol_menu, ui.wcol_pulldown, ui.wcol_tab]:
    if hasattr(w, 'inner'): s(w, 'inner', bg_light)
    if hasattr(w, 'inner_sel'): s(w, 'inner_sel', accent)
    if hasattr(w, 'item'): s(w, 'item', fg)
    if hasattr(w, 'text'): s(w, 'text', fg)
bpy.ops.wm.save_userpref()
"""
    import tempfile
    with tempfile.NamedTemporaryFile('w', suffix='.py', delete=False) as f:
        f.write(script_content)
        temp_path = f.name
    subprocess.run(["blender", "-b", "-P", temp_path], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    os.remove(temp_path)

def write_godot(palette):
    godot_settings = list(Path.home().glob(".config/godot/editor_settings-*.tres"))
    if not godot_settings: return
    
    def hex_to_color(hex_str):
        hex_str = hex_str.lstrip('#')
        r, g, b = (int(hex_str[i:i+2], 16)/255.0 for i in (0, 2, 4))
        return f"Color({r:.3f}, {g:.3f}, {b:.3f}, 1)"
        
    base_color = hex_to_color(palette["base"])
    accent_color = hex_to_color(palette["iris"])
    
    for path in godot_settings:
        content = path.read_text()
        content = re.sub(r'interface/theme/base_color\s*=\s*Color\([^)]+\)', f'interface/theme/base_color = {base_color}', content)
        content = re.sub(r'interface/theme/accent_color\s*=\s*Color\([^)]+\)', f'interface/theme/accent_color = {accent_color}', content)
        content = re.sub(r'interface/theme/color_preset\s*=\s*".*"', 'interface/theme/color_preset = "Custom"', content)
        path.write_text(content)

def write_obs(palette):
    obs_theme_dir = Path.home() / ".config/obs-studio/themes"
    obs_theme_dir.mkdir(parents=True, exist_ok=True)
    
    def rgb_str(hex_c):
        r, g, b = hex_to_rgb(hex_c)
        return f"rgb({r},{g},{b})"
        
    def darken(hex_c, amount=10):
        return morandi(hex_c, 0, -amount, 0, 100)

    obs_iris = darken(palette['iris'], 12)
    obs_foam = darken(palette['foam'], 12)
    obs_sky = darken(palette['sky'], 12)

    content = f"""@OBSThemeMeta {{
    name: 'Morandi';
    id: 'com.obsproject.Yami.Morandi';
    extends: 'com.obsproject.Yami';
    author: 'morandi-gen';
    dark: 'true';
}}

@OBSThemeVars {{
    --primary: {rgb_str(obs_iris)};
    --primary_light: {rgb_str(obs_foam)};
    --primary_lighter: {rgb_str(obs_sky)};
    --primary_dark: {rgb_str(palette['pine'])};
    --primary_darker: {rgb_str(palette['base'])};

    --blue1: {rgb_str(obs_sky)};
    --blue2: {rgb_str(obs_foam)};
    --blue3: {rgb_str(obs_iris)};
    --blue4: {rgb_str(palette['pine'])};
    --blue5: {rgb_str(palette['surface1'])};
    --blue6: {rgb_str(palette['surface0'])};

    --bg_base: {rgb_str(palette['mantle'])};
    --bg_window: {rgb_str(palette['base'])};
    --bg_preview: {rgb_str(palette['mantle'])};

    --border_color: {rgb_str(palette['surface1'])};

    --input_bg: {rgb_str(palette['surface0'])};
    --input_bg_hover: {rgb_str(palette['surface1'])};
    --input_bg_focus: {rgb_str(palette['surface1'])};

    --list_item_bg_selected: {rgb_str(palette['surface0'])};
    --list_item_bg_hover: {rgb_str(palette['surface1'])};

    --input_border: {rgb_str(palette['surface2'])};
    --input_border_hover: {rgb_str(obs_iris)};
    --input_border_focus: {rgb_str(obs_iris)};

    --button_bg: {rgb_str(palette['surface0'])};
    --button_bg_hover: {rgb_str(palette['surface1'])};
    --button_bg_down: {rgb_str(palette['surface2'])};
    --button_bg_disabled: {rgb_str(palette['mantle'])};

    --button_bg_red: {rgb_str(palette['love'])};
    --button_bg_red_hover: {rgb_str(palette['rose'])};
    --button_bg_red_down: {rgb_str(palette['love'])};

    --button_border: {rgb_str(palette['surface2'])};
    --button_border_hover: {rgb_str(obs_iris)};
    --button_border_focus: {rgb_str(obs_iris)};

    --tab_bg: {rgb_str(palette['surface0'])};
    --tab_bg_hover: {rgb_str(palette['surface1'])};
    --tab_bg_down: {rgb_str(palette['surface2'])};
    --tab_bg_disabled: {rgb_str(palette['mantle'])};

    --tab_border: {rgb_str(palette['surface0'])};
    --tab_border_hover: {rgb_str(palette['surface2'])};
    --tab_border_focus: {rgb_str(palette['surface2'])};
    --tab_border_selected: {rgb_str(obs_iris)};

    --scrollbar_handle: {rgb_str(palette['surface1'])};
    --scrollbar_hover: {rgb_str(palette['surface2'])};
    --scrollbar_down: {rgb_str(palette['surface0'])};
    --scrollbar_border: {rgb_str(palette['surface1'])};

    --toolbutton_bg: {rgb_str(palette['surface0'])};
    --toolbutton_bg_hover: {rgb_str(palette['surface1'])};
    --toolbutton_bg_down: {rgb_str(palette['surface2'])};
    --toolbutton_bg_disabled: {rgb_str(palette['mantle'])};
}}
"""
    (obs_theme_dir / "Yami_Morandi.ovt").write_text(content)
    
    obs_config = Path.home() / ".config/obs-studio/global.ini"
    if obs_config.exists():
        conf = obs_config.read_text()
        conf = re.sub(r"^CurrentTheme3=.*", "CurrentTheme3=Yami_Morandi", conf, flags=re.MULTILINE)
        obs_config.write_text(conf)

def write_clash_verge(palette):
    config_path = Path.home() / ".local/share/io.github.clash-verge-rev.clash-verge-rev/verge.yaml"
    if not config_path.exists():
        return

    content = config_path.read_text()

    css = f""":root {{
  --joy-palette-background-body: {palette['base']} !important;
  --joy-palette-background-surface: {palette['surface0']} !important;
  --joy-palette-background-level1: {palette['surface1']} !important;
  --joy-palette-background-level2: {palette['surface2']} !important;
  --joy-palette-background-level3: {palette['overlay0']} !important;
  --mui-palette-background-default: {palette['base']} !important;
  --mui-palette-background-paper: {palette['surface0']} !important;
  --bg-base: {palette['base']} !important;
  --bg-surface: {palette['surface0']} !important;
  --mui-palette-primary-contrastText: #ffffff !important;
  --joy-palette-primary-solidColor: #ffffff !important;
}}
body, #root, main, .MuiDrawer-paper, .MuiAppBar-root, .layout-content, .page, .page-content {{
  background-color: {palette['base']} !important;
  background-image: none !important;
  color: {palette['text']} !important;
}}
.MuiPaper-root, .MuiCard-root, .MuiDialog-paper, .MuiPopover-paper {{
  background-color: {palette['surface0']} !important;
  background-image: none !important;
  border-radius: 12px !important;
  border: 1px solid {palette['surface1']} !important;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.15) !important;
}}
.Mui-selected, .Mui-selected *, .MuiButton-containedPrimary, .MuiButton-containedPrimary *, .clash-active {{
  color: #ffffff !important;
}}
* {{
  transition: background-color 0.4s cubic-bezier(0.4, 0, 0.2, 1), 
              border-color 0.4s cubic-bezier(0.4, 0, 0.2, 1),
              color 0.4s cubic-bezier(0.4, 0, 0.2, 1),
              box-shadow 0.4s cubic-bezier(0.4, 0, 0.2, 1),
              transform 0.3s cubic-bezier(0.4, 0, 0.2, 1) !important;
}}
.MuiButtonBase-root:hover, .MuiMenuItem-root:hover, .clash-hover-effect:hover {{
  transform: translateY(-2px) !important;
  box-shadow: 0 6px 16px rgba(0,0,0,0.2) !important;
}}
.MuiButtonBase-root:active, .MuiMenuItem-root:active, .clash-hover-effect:active {{
  transform: translateY(1px) !important;
  box-shadow: none !important;
}}"""

    css_indented = "\n    ".join(css.split("\n"))
    
    theme_setting = f"theme_setting:\n  primary_color: '{palette['iris']}'\n  secondary_color: '{palette['foam']}'\n  info_color: '{palette['sky']}'\n  error_color: '{palette['love']}'\n  warning_color: '{palette['gold']}'\n  success_color: '{palette['pine']}'\n  css_injection: |\n    {css_indented}"
    
    if "theme_setting: null" in content:
        content = re.sub(r"^theme_setting:\s*null", theme_setting, content, flags=re.MULTILINE)
    elif re.search(r"^theme_setting:", content, flags=re.MULTILINE):
        content = re.sub(r"^theme_setting:.*(\n\s+.*)*", theme_setting, content, flags=re.MULTILINE)
    else:
        content += "\n" + theme_setting + "\n"
        
    content = re.sub(r"^css_injection:.*(\n\s+.*)*", "", content, flags=re.MULTILINE).strip() + "\n"
        
    config_path.write_text(content)




def apply_system_changes(wallpaper_path=None):
    def run_ignore_missing(*args, **kwargs):
        try:
            subprocess.run(*args, **kwargs)
        except FileNotFoundError:
            pass

    env = os.environ.copy()
    env["DISPLAY"] = ":0"
    env["XDG_RUNTIME_DIR"] = f"/run/user/{os.getuid()}"
    run_ignore_missing(["dbus-send", "--session", "--dest=org.kde.plasmashell", "--type=method_call", "/PlasmaShell", "org.kde.PlasmaShell.evaluateScript", "string: var allDesktops = desktops(); for (var i=0; i<allDesktops.length; i++) { allDesktops[i].wallpaperPlugin = '' }"], env=env, stderr=subprocess.DEVNULL)
    run_ignore_missing(["qdbus", "org.kde.KWin", "/KWin", "reconfigure"], env=env, stderr=subprocess.DEVNULL)
    run_ignore_missing(["niri", "msg", "action", "load-config-file"], stderr=subprocess.DEVNULL)
    
    if wallpaper_path and Path(wallpaper_path).exists():
        efi_dir = "/boot/efi"
        subprocess.run(["sudo", "magick", wallpaper_path, "-blur", "0x12", "-resize", "1920x1080!", "-quality", "95", f"{efi_dir}/limine_bg.png"], stderr=subprocess.DEVNULL)
        
    try:
        pid = subprocess.check_output(["pgrep", "-x", "fcitx5"]).decode().strip()
        if pid:
            subprocess.run(["kill", pid])
            subprocess.run(["sleep", "0.3"])
    except subprocess.CalledProcessError:
        pass
    subprocess.Popen(["fcitx5"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, start_new_session=True)

def write_flclash(palette):
    config_path = Path.home() / ".local/share/com.follow.clash/shared_preferences.json"
    if not config_path.exists():
        return
        
    try:
        with open(config_path, "r") as f:
            data = json.load(f)
            
        if "flutter.config" in data:
            flutter_config = json.loads(data["flutter.config"])
            
            hex_color = palette['iris'].lstrip('#')
            if len(hex_color) == 6:
                argb_int = int("ff" + hex_color, 16)
            else:
                argb_int = int(hex_color, 16)
                
            if "themeProps" not in flutter_config:
                flutter_config["themeProps"] = {}
                
            flutter_config["themeProps"]["primaryColor"] = argb_int
            flutter_config["themeProps"]["pureBlack"] = False
            flutter_config["themeProps"]["themeMode"] = "dark"
            
            data["flutter.config"] = json.dumps(flutter_config, separators=(',', ':'))
            
            with open(config_path, "w") as f:
                json.dump(data, f, separators=(',', ':'))
    except Exception as e:
        print(f"Failed to write flclash theme: {e}")

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--wallpaper", help="Path to current wallpaper for limine sync")
    args = parser.parse_args()

    if not NOCTALIA_COLORS.exists():
        print(f"Error: {NOCTALIA_COLORS} not found")
        sys.exit(1)

    with open(NOCTALIA_COLORS) as f:
        colors = json.load(f)

    palette = generate_palette(colors)
    write_niri(palette)
    write_starship(palette)
    write_fcitx5(palette)
    write_fastfetch(palette)
    write_alacritty()
    write_kde(colors)
    write_clash_verge(palette)
    write_flclash(palette)
    write_vscode(palette)
    
    try:
        write_blender(palette)
    except Exception as e:
        print(f"Failed to write blender theme: {e}")
        
    try:
        write_godot(palette)
    except Exception as e:
        print(f"Failed to write godot theme: {e}")
        

    try:
        write_obs(palette)
    except Exception as e:
        print(f"Failed to write obs theme: {e}")

    try:
        write_clash_verge(palette)
    except Exception as e:
        print(f"Failed to write clash verge theme: {e}")


    apply_system_changes(args.wallpaper)
    print("Morandi theme generated and system changes applied successfully.")

if __name__ == "__main__":
    main()
