#!/usr/bin/env python3
"""Generate Morandi-style color palette from Noctalia's Material You colors."""

import json
import colorsys
import os
import re
import sys

NOCTALIA_COLORS = os.path.expanduser("~/.config/noctalia/colors.json")
NIRI_COLORS_KDL = os.path.expanduser("~/.config/niri/cfg/colors.kdl")
STARSHIP_TOML = os.path.expanduser("~/.config/starship.toml")
FCITX5_THEME = os.path.expanduser("~/.local/share/fcitx5/themes/morandi/theme.conf")
FASTFETCH_CONFIG = os.path.expanduser("~/.config/fastfetch/config.jsonc")
ALACRITTY_TOML = os.path.expanduser("~/.config/alacritty/alacritty.toml")


def hex_to_hsl(hex_color):
    r = int(hex_color[1:3], 16) / 255
    g = int(hex_color[3:5], 16) / 255
    b = int(hex_color[5:7], 16) / 255
    h, l, s = colorsys.rgb_to_hls(r, g, b)
    return h * 360, s * 100, l * 100


def hsl_to_hex(h, s, l):
    h = h % 360
    s = max(0, min(100, s)) / 100
    l = max(0, min(100, l)) / 100
    r, g, b = colorsys.hls_to_rgb(h / 360, l, s)
    return f"#{int(r*255):02x}{int(g*255):02x}{int(b*255):02x}"


def morandi(hex_color, sat_reduction=0.3, light_adjust=0, warm_shift=0, sat_cap=45):
    h, s, l = hex_to_hsl(hex_color)
    s = s * (1 - sat_reduction)
    h = (h + warm_shift) % 360
    l = max(0, min(100, l + light_adjust))
    s = min(s, sat_cap)
    return hsl_to_hex(h, s, l)


def blend(c1, c2, ratio=0.5):
    r1, g1, b1 = int(c1[1:3], 16), int(c1[3:5], 16), int(c1[5:7], 16)
    r2, g2, b2 = int(c2[1:3], 16), int(c2[3:5], 16), int(c2[5:7], 16)
    r = int(r1 + (r2 - r1) * ratio)
    g = int(g1 + (g2 - g1) * ratio)
    b = int(b1 + (b2 - b1) * ratio)
    return f"#{r:02x}{g:02x}{b:02x}"


def generate_palette(c):
    p = {}
    primary = c["mPrimary"]
    secondary = c["mSecondary"]
    tertiary = c["mTertiary"]
    error = c["mError"]
    surface = c["mSurface"]
    on_surface = c["mOnSurface"]
    surface_var = c["mSurfaceVariant"]
    outline = c["mOutline"]

    p["base"] = morandi(surface, 0.5, -2)
    p["mantle"] = morandi(surface, 0.6, -5)
    p["surface0"] = morandi(surface_var, 0.4, 2)
    p["surface1"] = morandi(surface_var, 0.3, 5)
    p["surface2"] = morandi(surface_var, 0.2, 8)
    p["overlay0"] = morandi(outline, 0.3, -2)
    p["overlay1"] = morandi(outline, 0.2, 2)
    p["overlay2"] = morandi(outline, 0.1, 5)
    p["subtext0"] = morandi(on_surface, 0.4, -8)
    p["subtext1"] = morandi(on_surface, 0.3, -4)
    p["text"] = morandi(on_surface, 0.2, 0)
    p["love"] = morandi(error, 0.25, -15)
    p["rose"] = morandi(blend(primary, error, 0.6), 0.3, -15, 5)
    p["gold"] = morandi(blend(primary, "#d4a574", 0.3), 0.35, -10, 15)
    p["peach"] = morandi(blend(error, "#d4a574", 0.4), 0.3, -10, 10)
    p["pine"] = morandi(tertiary, 0.3, -18, -5)
    p["foam"] = morandi(secondary, 0.35, -18, -5)
    p["iris"] = morandi(primary, 0.25, -18)
    p["sky"] = morandi(tertiary, 0.35, -18, -10)

    # Derive fcitx5-specific colors from the palette
    h, s, l = hex_to_hsl(p["surface1"])
    p["fcitx5_bg"] = hsl_to_hex(h, s * 0.6, min(l, 20))
    p["fcitx5_bg_alt"] = hsl_to_hex(h, s * 0.5, min(l + 3, 22))
    # highlight background: keep hue from iris, but cap lightness at 38%
    ih, is_, il = hex_to_hsl(p["iris"])
    p["fcitx5_hl_bg"] = hsl_to_hex(ih, is_, min(il, 38))
    p["fcitx5_text"] = p["text"]
    p["fcitx5_hl_text"] = p["base"]
    return p


def write_niri(palette):
    kdl = f"""// Auto-generated by morandi-gen.py — do not edit manually
// Morandi palette derived from Noctalia wallpaper colors
layout {{
    focus-ring {{
        width 2
        active-gradient from="{palette['iris']}" to="{palette['pine']}" angle=45
        inactive-gradient from="{palette['surface0']}" to="{palette['surface1']}" angle=45
    }}
    border {{
        off
    }}
}}
"""
    with open(NIRI_COLORS_KDL, "w") as f:
        f.write(kdl)


def write_starship(palette):
    with open(STARSHIP_TOML, "r") as f:
        content = f.read()

    keys = [
        "base", "mantle", "surface0", "surface1", "surface2",
        "overlay0", "overlay1", "overlay2", "subtext0", "subtext1", "text",
        "love", "gold", "peach", "rose", "pine", "foam", "iris", "sky",
    ]
    new_palette = "[palettes.custom]\n"
    for k in keys:
        new_palette += f"{k} = '{palette[k]}'\n"

    pattern = r"\[palettes\.custom\][\s\S]*?(?=\n\[|\Z)"
    replacement = new_palette
    new_content, count = re.subn(pattern, replacement, content)
    if count == 0:
        new_content = content + "\n" + new_palette

    with open(STARSHIP_TOML, "w") as f:
        f.write(new_content)


def write_fcitx5(palette):
    theme_dir = os.path.dirname(FCITX5_THEME)
    os.makedirs(theme_dir, exist_ok=True)

    # Use surface0 (lightest dark) for tray outline, text for tray text
    tray_outline = palette["surface0"]
    tray_text = palette["text"]

    # Generate SVG files for rounded corners
    bg = palette['fcitx5_bg']
    hl = palette['fcitx5_hl_bg']
    # Derive a slightly lighter border color for the stroke
    bh, bs, bl = hex_to_hsl(bg)
    border = hsl_to_hex(bh, bs, min(bl + 5, 100))
    hh, hs, hl_val = hex_to_hsl(hl)
    hborder = hsl_to_hex(hh, hs, min(hl_val + 5, 100))

    panel_svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="40" height="100">
    <g>
        <title>Layer 1</title>
        <rect id="svg_1" width="39" height="99" x=".5" y=".5" fill="{bg}" stroke="{border}" rx="10" ry="10"/>
    </g>
</svg>'''
    highlight_svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="39" height="44">
    <g id="Layer_1">
        <title>Layer 1</title>
        <rect id="svg_1" width="39" height="44" x="0" y="0" fill="{hl}" stroke="{hborder}" stroke-width="0" rx="8" ry="8"/>
    </g>
</svg>'''

    with open(os.path.join(theme_dir, "panel.svg"), "w") as f:
        f.write(panel_svg)
    with open(os.path.join(theme_dir, "highlight.svg"), "w") as f:
        f.write(highlight_svg)

    theme = f"""[Metadata]
Name=morandi
Version=0.0.3
Author=morandi-gen
Description=Auto-generated Morandi theme

[InputPanel]
NormalColor={palette['fcitx5_text']}
HighlightColor={palette['fcitx5_hl_text']}
HighlightBackgroundColor={palette['fcitx5_hl_bg']}
HighlightCandidateColor={palette['fcitx5_text']}
EnableBlur=True
FullWidthHighlight=True
PageButtonAlignment=Bottom

[InputPanel/BlurMargin]
Left=0
Right=0
Top=0
Bottom=0

[InputPanel/Background]
Image=panel.svg
Color={palette['fcitx5_bg']}
BorderColor={palette['fcitx5_bg']}
BorderWidth=0
Overlay=
Gravity="Top Left"
OverlayOffsetX=0
OverlayOffsetY=0
HideOverlayIfOversize=False

[InputPanel/Background/Margin]
Left=6
Right=6
Top=6
Bottom=6

[InputPanel/Background/OverlayClipMargin]
Left=0
Right=0
Top=0
Bottom=0

[InputPanel/Highlight]
Image=highlight.svg
Color={palette['fcitx5_hl_bg']}
BorderColor={palette['fcitx5_hl_bg']}00
BorderWidth=0
Overlay=
Gravity="Top Left"
OverlayOffsetX=0
OverlayOffsetY=0
HideOverlayIfOversize=False

[InputPanel/Highlight/Margin]
Left=4
Right=4
Top=3
Bottom=3

[InputPanel/Highlight/OverlayClipMargin]
Left=0
Right=0
Top=0
Bottom=0

[InputPanel/Highlight/HighlightClickMargin]
Left=0
Right=0
Top=0
Bottom=0

[InputPanel/ContentMargin]
Left=0
Right=0
Top=0
Bottom=0

[InputPanel/TextMargin]
Left=8
Right=8
Top=4
Bottom=4

[InputPanel/PrevPage]
Image=

[InputPanel/PrevPage/ClickMargin]
Left=0
Right=0
Top=0
Bottom=0

[InputPanel/NextPage]
Image=

[InputPanel/NextPage/ClickMargin]
Left=0
Right=0
Top=0
Bottom=0

[InputPanel/ShadowMargin]
Left=0
Right=0
Top=0
Bottom=0

[Menu]
NormalColor={palette['fcitx5_text']}
HighlightCandidateColor={palette['fcitx5_text']}
Spacing=0

[Menu/Background]
Image=panel.svg
Color={palette['fcitx5_bg']}
BorderColor={palette['fcitx5_bg']}00
BorderWidth=0
Overlay=
Gravity="Top Left"
OverlayOffsetX=0
OverlayOffsetY=0
HideOverlayIfOversize=False

[Menu/Background/Margin]
Left=4
Right=4
Top=4
Bottom=4

[Menu/Background/OverlayClipMargin]
Left=0
Right=0
Top=0
Bottom=0

[Menu/Highlight]
Image=highlight.svg
Color={palette['fcitx5_hl_bg']}
BorderColor={palette['fcitx5_hl_bg']}00
BorderWidth=0
Overlay=
Gravity="Top Left"
OverlayOffsetX=0
OverlayOffsetY=0
HideOverlayIfOversize=False

[Menu/Highlight/Margin]
Left=2
Right=2
Top=1
Bottom=1

[Menu/Highlight/OverlayClipMargin]
Left=0
Right=0
Top=0
Bottom=0

[Menu/Separator]
Image=
Color={palette['fcitx5_bg_alt']}
BorderColor={palette['fcitx5_bg_alt']}00
BorderWidth=0
Overlay=
Gravity="Top Left"
OverlayOffsetX=0
OverlayOffsetY=0
HideOverlayIfOversize=False

[Menu/Separator/Margin]
Left=0
Right=0
Top=0
Bottom=0

[Menu/Separator/OverlayClipMargin]
Left=0
Right=0
Top=0
Bottom=0

[Menu/CheckBox]
Image=
Color={palette['fcitx5_bg']}
BorderColor={palette['fcitx5_bg']}00
BorderWidth=0
Overlay=
Gravity="Top Left"
OverlayOffsetX=0
OverlayOffsetY=0
HideOverlayIfOversize=False

[Menu/CheckBox/Margin]
Left=0
Right=0
Top=0
Bottom=0

[Menu/CheckBox/OverlayClipMargin]
Left=0
Right=0
Top=0
Bottom=0

[Menu/SubMenu]
Image=
Color={palette['fcitx5_bg']}
BorderColor={palette['fcitx5_bg']}00
BorderWidth=0
Overlay=
Gravity="Top Left"
OverlayOffsetX=0
OverlayOffsetY=0
HideOverlayIfOversize=False

[Menu/SubMenu/Margin]
Left=0
Right=0
Top=0
Bottom=0

[Menu/SubMenu/OverlayClipMargin]
Left=0
Right=0
Top=0
Bottom=0

[Menu/ContentMargin]
Left=0
Right=0
Top=0
Bottom=0

[Menu/TextMargin]
Left=0
Right=0
Top=0
Bottom=0
"""
    with open(FCITX5_THEME, "w") as f:
        f.write(theme)

    # Update classicui.conf to point to the morandi theme
    classicui = os.path.expanduser("~/.config/fcitx5/conf/classicui.conf")
    if os.path.exists(classicui):
        with open(classicui, "r") as f:
            content = f.read()
        content = re.sub(r"^Theme=.*", "Theme=morandi", content, flags=re.MULTILINE)
        content = re.sub(r"^DarkTheme=.*", "DarkTheme=morandi", content, flags=re.MULTILINE)
        content = re.sub(r"^UseDarkTheme=.*", "UseDarkTheme=False", content, flags=re.MULTILINE)
        content = re.sub(r"^TrayOutlineColor=.*", f"TrayOutlineColor={tray_outline}", content, flags=re.MULTILINE)
        content = re.sub(r"^TrayTextColor=.*", f"TrayTextColor={tray_text}", content, flags=re.MULTILINE)
        with open(classicui, "w") as f:
            f.write(content)


def write_fastfetch(palette):
    config = f"""{{
    "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
    "logo": {{
        "type": "chafa",
        "source": "{os.path.expanduser('~/.config/fastfetch/avatar.png')}",
        "width": 40,
        "height": 19,
        "padding": {{
            "top": 2,
            "right": 2
        }}
    }},
    "display": {{
        "separator": "  ",
        "color": {{
            "keys": "{palette['iris']}",
            "title": "{palette['text']}"
        }}
    }},
    "modules": [
        "title",
        "separator",
        {{
            "type": "os",
            "key": " \uf30e OS",
            "format": "{{name}} {{version}}"
        }},
        {{
            "type": "kernel",
            "key": " \uf331 Kernel",
            "format": "{{release}}"
        }},
        {{
            "type": "uptime",
            "key": " \uf017 Uptime"
        }},
        {{
            "type": "packages",
            "key": " \uf2dc Packages"
        }},
        {{
            "type": "shell",
            "key": " \uf489 Shell"
        }},
        {{
            "type": "terminal",
            "key": " \uf120 Terminal"
        }},
        {{
            "type": "de",
            "key": " \uf35e DE"
        }},
        {{
            "type": "wm",
            "key": " \uf2d2 WM"
        }},
        {{
            "type": "wmtheme",
            "key": " \uf042 WM Theme"
        }},
        "separator",
        {{
            "type": "host",
            "key": " \uf2db Host"
        }},
        {{
            "type": "cpu",
            "key": " \uf2db CPU"
        }},
        {{
            "type": "gpu",
            "key": " \uf26c GPU"
        }},
        {{
            "type": "memory",
            "key": " \uf0e4 Memory"
        }},
        {{
            "type": "disk",
            "key": " \uf0a0 Disk"
        }},
        "separator",
        {{
            "type": "localip",
            "key": " \uf0ac Local IP"
        }},
        "break",
        "colors"
    ]
}}"""
    with open(FASTFETCH_CONFIG, "w") as f:
        f.write(config)


ALACRITTY_ORIGINAL_NORMAL = {
    "black": "#1c1c1c", "red": "#ff6c6b", "green": "#98be65",
    "yellow": "#ecbe7b", "blue": "#51afef", "magenta": "#c678dd",
    "cyan": "#46d9ff", "white": "#bbc2cf",
}
ALACRITTY_ORIGINAL_BRIGHT = {
    "black": "#5b6268", "red": "#da8548", "green": "#4db5bd",
    "yellow": "#ecbe7b", "blue": "#3071db", "magenta": "#a9a1e1",
    "cyan": "#46d9ff", "white": "#dfdfdf",
}


def morandi_preserve_hue(hex_color, sat_reduction=0.45, light_adjust=-5, sat_cap=40):
    h, s, l = hex_to_hsl(hex_color)
    s = s * (1 - sat_reduction)
    l = max(0, min(100, l + light_adjust))
    s = min(s, sat_cap)
    return hsl_to_hex(h, s, l)


def write_alacritty(palette):
    with open(ALACRITTY_TOML, "r") as f:
        content = f.read()

    normal_colors = ""
    for name, orig in ALACRITTY_ORIGINAL_NORMAL.items():
        mor = morandi_preserve_hue(orig)
        normal_colors += f'{name} = "{mor}"\n'

    bright_colors = ""
    for name, orig in ALACRITTY_ORIGINAL_BRIGHT.items():
        mor = morandi_preserve_hue(orig)
        bright_colors += f'{name} = "{mor}"\n'

    content = re.sub(
        r"\[colors\.normal\]\n(.*?\n)+?(?=\[colors\.bright\])",
        f"[colors.normal]\n{normal_colors}\n",
        content, flags=re.MULTILINE
    )
    content = re.sub(
        r"\[colors\.bright\]\n(.*?\n)+?(?=\[colors\.cursor\])",
        f"[colors.bright]\n{bright_colors}\n",
        content, flags=re.MULTILINE
    )

    with open(ALACRITTY_TOML, "w") as f:
        f.write(content)


def main():
    if not os.path.exists(NOCTALIA_COLORS):
        print(f"Error: {NOCTALIA_COLORS} not found")
        sys.exit(1)

    with open(NOCTALIA_COLORS) as f:
        colors = json.load(f)

    palette = generate_palette(colors)
    write_niri(palette)
    write_starship(palette)
    write_fcitx5(palette)
    write_fastfetch(palette)
    write_alacritty(palette)

    print("Morandi palette generated:")
    for k, v in palette.items():
        print(f"  {k}: {v}")


if __name__ == "__main__":
    main()
