[Appearance]
color_scheme_path=/home/kogeki/.local/share/color-schemes/DankMatugen.colors
custom_palette=true
icon_theme=Adwaita

[Fonts]
fixed="Maple Mono NL NF CN,9,-1,5,50,0,0,0,0,0"
general="Inter,10,-1,5,50,0,0,0,0,0"

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x6\0\0\0\0\0\0\0\t\xb9\0\0\x3\xce\0\0\x6\0\0\0\0\0\0\0\t\xb9\0\0\x3\xce\0\0\0\0\0\0\0\0\a\x80\0\0\x6\0\0\0\0\0\0\0\t\xb9\0\0\x3\xce)
